---
sudo: required
dist: focal

language: c

addons:
  apt:
    packages:
    - python3-docutils
    - python3-sphinx
    - libmhash-dev

before_install:
  - set -e
  - wget $VARSNIH_TGZ
  - tar -zxf *gz
  - pushd varnish-*/
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make -sj32
  - sudo make install
  - popd

before_script:
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make -j4

script:
  - make check -j4

env:
  matrix:
    - VARSNIH_TGZ=https://github.com/varnishcache/varnish-cache/archive/master.tar.gz
    - VARSNIH_TGZ=https://varnish-cache.org/_downloads/varnish-6.5.0.tgz
    - VARSNIH_TGZ=https://varnish-cache.org/_downloads/varnish-6.4.0.tgz
    - VARSNIH_TGZ=https://varnish-cache.org/_downloads/varnish-6.3.0.tgz
    - VARSNIH_TGZ=https://varnish-cache.org/_downloads/varnish-6.2.1.tgz
    - VARSNIH_TGZ=https://varnish-cache.org/_downloads/varnish-6.0.4.tgz

compiler:
  - clang
  - gcc

matrix:
  allow_failures:
    - env: VARSNIH_TGZ=https://github.com/varnishcache/varnish-cache/archive/master.tar.gz
